name: Manual COPR Rebuild

on:
  # Manual trigger only
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force rebuild even if versions unchanged'
        required: false
        default: 'false'
        type: choice
        options:
        - 'true'
        - 'false'
      reason:
        description: 'Reason for manual rebuild'
        required: false
        default: 'Manual rebuild requested'

jobs:
  trigger-rebuild:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Configure git
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
    
    - name: Force version update
      if: inputs.force_rebuild == 'true'
      run: |
        chmod +x check_versions.sh
        
        echo "🔄 Forcing version update to trigger COPR rebuild"
        echo "Reason: ${{ inputs.reason }}"
        
        # Force update with custom commit message
        ./check_versions.sh --update --force || true
        
        # Add reason to commit message if changes were made
        if [ -n "$(git status --porcelain)" ]; then
          git add versions.json
          COMMIT_MSG="Force rebuild: ${{ inputs.reason }}
        
        Auto-update versions to trigger COPR rebuild
        Generated by manual workflow trigger"
          git commit --amend -m "$COMMIT_MSG"
          git push --force-with-lease origin main
        fi
    
    - name: Display rebuild info
      run: |
        echo "✅ Rebuild triggered"
        echo "📝 Reason: ${{ inputs.reason }}"
        echo "🔗 Check COPR build status at: https://copr.fedorainfracloud.org/coprs/YOUR_USERNAME/pushpin/"
        echo ""
        echo "Current versions:"
        cat versions.json